"""empty message

Revision ID: c6b7b5388c04
Revises: 
Create Date: 2025-10-14 15:57:38.081144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6b7b5388c04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refuse_news', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='资讯标题',
               existing_nullable=False)
        batch_op.alter_column('subtitle',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='副标题',
               existing_nullable=True)
        batch_op.alter_column('publish_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='发布日期',
               existing_nullable=False)
        batch_op.alter_column('author',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='作者',
               existing_nullable=True)
        batch_op.alter_column('source',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='来源',
               existing_nullable=True)
        batch_op.alter_column('views',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='浏览量',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('likes',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='点赞数',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='分类',
               existing_nullable=True)
        batch_op.alter_column('coverImage',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='封面图片',
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               comment=None,
               existing_comment='资讯内容',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_table_comment(
        existing_comment='垃圾资讯表'
    )

    with op.batch_alter_table('refuse_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refuse_types', schema=None) as batch_op:
        batch_op.drop_column('color')

    with op.batch_alter_table('refuse_news', schema=None) as batch_op:
        batch_op.create_table_comment(
        '垃圾资讯表',
        existing_comment=None
    )
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               comment='资讯内容',
               existing_nullable=False)
        batch_op.alter_column('coverImage',
               existing_type=mysql.VARCHAR(length=255),
               comment='封面图片',
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=50),
               comment='分类',
               existing_nullable=True)
        batch_op.alter_column('likes',
               existing_type=mysql.INTEGER(),
               comment='点赞数',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('views',
               existing_type=mysql.INTEGER(),
               comment='浏览量',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('source',
               existing_type=mysql.VARCHAR(length=100),
               comment='来源',
               existing_nullable=True)
        batch_op.alter_column('author',
               existing_type=mysql.VARCHAR(length=100),
               comment='作者',
               existing_nullable=True)
        batch_op.alter_column('publish_date',
               existing_type=sa.DATE(),
               comment='发布日期',
               existing_nullable=False)
        batch_op.alter_column('subtitle',
               existing_type=mysql.VARCHAR(length=255),
               comment='副标题',
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               comment='资讯标题',
               existing_nullable=False)

    # ### end Alembic commands ###
